In [1]:
import numpy as np
import pandas as pd
data_fake = pd.DataFrame(
    {
        'items':[np.nan,2,4,8,10],
        'age':[23,np.nan,28,32,40],
        'cost':[9500, 11000, np.nan, np.nan, 14760]
     },
     )

In [2]:
data_fake.head()

items   age     cost
0    NaN  23.0   9500.0
1    2.0   NaN  11000.0
2    4.0  28.0      NaN
3    8.0  32.0      NaN
4   10.0  40.0  14760.0

In [3]:
from sklearn.impute import SimpleImputer
imp_median = SimpleImputer(missing_values=np.nan, strategy='median')

In [6]:
imp_median.fit_transform(data_fake)

array([[6.000e+00, 2.300e+01, 9.500e+03],
       [2.000e+00, 3.000e+01, 1.100e+04],
       [4.000e+00, 2.800e+01, 1.100e+04],
       [8.000e+00, 3.200e+01, 1.100e+04],
       [1.000e+01, 4.000e+01, 1.476e+04]])

In [7]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit_transform(data_fake)

array([[6.00000000e+00, 2.30000000e+01, 9.50000000e+03],
       [2.00000000e+00, 3.07500000e+01, 1.10000000e+04],
       [4.00000000e+00, 2.80000000e+01, 1.17533333e+04],
       [8.00000000e+00, 3.20000000e+01, 1.17533333e+04],
       [1.00000000e+01, 4.00000000e+01, 1.47600000e+04]])

In [8]:
imp_median_indicator = SimpleImputer(missing_values=np.nan, strategy='median', add_indicator=True)

In [9]:
imp_median_indicator.fit_transform(data_fake)

array([[6.000e+00, 2.300e+01, 9.500e+03, 1.000e+00, 0.000e+00, 0.000e+00],
       [2.000e+00, 3.000e+01, 1.100e+04, 0.000e+00, 1.000e+00, 0.000e+00],
       [4.000e+00, 2.800e+01, 1.100e+04, 0.000e+00, 0.000e+00, 1.000e+00],
       [8.000e+00, 3.200e+01, 1.100e+04, 0.000e+00, 0.000e+00, 1.000e+00],
       [1.000e+01, 4.000e+01, 1.476e+04, 0.000e+00, 0.000e+00, 0.000e+00]])

In [10]:
data_fake = pd.DataFrame(
    {
        'items':[np.nan,2,4,8,10, 9],
        'age':[23,np.nan,28,32,40, 35],
        'cost':[9500, 11000, 12000, np.nan, 14760, 13500]
     },
     )

In [19]:
data_fake

items   age     cost
0    NaN  23.0   9500.0
1    2.0   NaN  11000.0
2    4.0  28.0  12000.0
3    8.0  32.0      NaN
4   10.0  40.0  14760.0
5    9.0  35.0  13500.0

In [12]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [13]:
ii = IterativeImputer()
ii.fit_transform(data_fake)

array([[-1.05875615e+00,  2.30000000e+01,  9.50000000e+03],
       [ 2.00000000e+00,  2.66381993e+01,  1.10000000e+04],
       [ 4.00000000e+00,  2.80000000e+01,  1.20000000e+04],
       [ 8.00000000e+00,  3.20000000e+01,  1.30629587e+04],
       [ 1.00000000e+01,  4.00000000e+01,  1.47600000e+04],
       [ 9.00000000e+00,  3.50000000e+01,  1.35000000e+04]])

In [17]:
from sklearn.impute import KNNImputer
knn_imp = KNNImputer()
knn_imp.fit_transform(data_fake)

array([[6.6000e+00, 2.3000e+01, 9.5000e+03],
       [2.0000e+00, 3.1600e+01, 1.1000e+04],
       [4.0000e+00, 2.8000e+01, 1.2000e+04],
       [8.0000e+00, 3.2000e+01, 1.2152e+04],
       [1.0000e+01, 4.0000e+01, 1.4760e+04],
       [9.0000e+00, 3.5000e+01, 1.3500e+04]])

In [18]:
from sklearn.impute import KNNImputer
knn_imp = KNNImputer(n_neighbors=2)
knn_imp.fit_transform(data_fake)

array([[5.000e+00, 2.300e+01, 9.500e+03],
       [2.000e+00, 3.000e+01, 1.100e+04],
       [4.000e+00, 2.800e+01, 1.200e+04],
       [8.000e+00, 3.200e+01, 1.275e+04],
       [1.000e+01, 4.000e+01, 1.476e+04],
       [9.000e+00, 3.500e+01, 1.350e+04]])

**End Webinar**